---
title: "main"
output: html_document
date: "2022-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(ggplot2)
library(lubridate)
library(stringr)
library(tidyr)
library(rjags)
```

Data from:
Indiegogo projects
https://webrobots.io/indiegogo-dataset/
Kickstarter projects
https://www.icpsr.umich.edu/web/NADAC/studies/38050
Currency exchange rates
https://www.imf.org/external/np/fin/ert/GUI/Pages/ReportOptions.aspx

```{r filter_ig_data}

ig_data = read_csv("data/Indiegogo.csv")


ig_data = ig_data %>% 
  select(category, close_date, currency, funds_raised_amount, funds_raised_percent, open_date, project_id, project_type, tags, title) %>% 
  mutate(close_date = as.Date(sub("T.*","",close_date)),
         open_date = as.Date(sub("T.*","",open_date)),
         goal = funds_raised_amount/funds_raised_percent,
         raised_frac = funds_raised_percent,
         state = if_else(funds_raised_percent >= 1, "successful", "failed"))

```

```{r utility functions}

as_dollar_str = function(n){
  return(paste0("$",format(n, scientific = FALSE, big.mark = ",", trim = TRUE)))
}

as_dollar_str(10^(1:7))

```

```{r clean_ks_data}

ks_data = read_csv("data/ICPSR_ks.csv")

ks_data = ks_data %>% 
  mutate(project_id = PID,
         category = CATEGORY,
         category_id = CATEGORY_ID,
         subcategory = SUBCATEGORY,
         subcategory_id = SUBCATEGORY_ID,
         open_date = mdy(LAUNCHED_DATE),
         close_date = mdy(DEADLINE_DATE),
         currency = PROJECT_CURRENCY,
         goal = GOAL_IN_ORIGINAL_CURRENCY,
         pledged = PLEDGED_IN_ORIGINAL_CURRENCY,
         goal_usd = as.double(gsub("[$,]","",GOAL_IN_USD)),
         pledged_usd = as.double(gsub("[$,]","",PLEDGED_IN_USD)),
         backers = BACKERS_COUNT,
         state = STATE,
         raised_frac = pledged/goal,
         .keep = "none") %>% 
  filter(goal > 0)

```


```{r exchange rates}

usd_exchange = read_csv("data/Exchange_Rate_Report_IMF.csv") %>% 
  mutate(month = floor_date(dmy(Date), "month"), .keep = "unused") %>% 
  group_by(month) %>% 
  summarise(across(.cols = everything(), ~ mean(.x, na.rm = TRUE)))

currency_names = str_extract(str_extract(colnames(usd_exchange), "\\(.*\\)"), "[A-Z]{3}")
i_currency = match(ig_data$currency, currency_names)
i_month = match(floor_date(ig_data$open_date, unit = "month"), usd_exchange$month)
rates = as.double(data.frame(usd_exchange)[cbind(i_month, i_currency)])

ig_data = ig_data %>% 
  mutate(pledged_usd = rates*funds_raised_amount,
         goal_usd = rates*goal)


```


```{r generalization}
gen_lookup = read_csv("general categories.csv")

ig_data = ig_data %>%
  mutate(category_broad = slice(gen_lookup, match(category, gen_lookup$Specific))$General)

ks_data = ks_data %>% 
  mutate(category_broad = slice(gen_lookup, match(category, gen_lookup$Specific))$General)

```

```{r exploration}
ks_data %>% 
  group_by(category_broad) %>% 
  summarize(success_rate = mean(state == "successful"),
            mean_funding_rate = mean(raised_frac, na.rm = T),
            median_funding_rate = median(raised_frac, na.rm = T),
            count  = n())


ig_data %>% 
  group_by(category_broad) %>% 
  summarize(success_rate = mean(state == "successful"),
            mean_funding_rate = mean(funds_raised_percent, na.rm = T),
            median_funding_rate = median(funds_raised_percent, na.rm = T),
            count  = n())

ig_data %>% 
  group_by(category) %>% 
  summarize(n(),
            min(close_date, na.rm = T),
            max(close_date, na.rm = T))

ks_data %>% 
  group_by(category_broad) %>% 
  summarize(success_rate = mean(state == "successful"),
            mean_funding_rate = mean(raised_frac),
            median_funding_rate = median(raised_frac),
            median_goal = median(goal_usd),
            count  = n())


ig_data %>% 
  filter(is.na(open_date))

```



```{r category analysis}
platform_colors = c(Kickstarter = "#04cc7b", Indiegogo = "#e41474")

ks_cat_summary = ks_data %>% 
  group_by(category_broad) %>% 
  summarize(success_rate = mean(state == "successful"),
            mean_funding_rate = mean(raised_frac, na.rm = T),
            median_funding_rate = median(raised_frac, na.rm = T),
            median_goal = median(goal_usd, na.rm = T),
            median_raised = median(pledged_usd, na.rm = T),
            count  = n()) %>% 
  mutate(platform = "Kickstarter")

ig_cat_summary = ig_data %>% 
  group_by(category_broad) %>% 
  summarize(success_rate = mean(state == "successful"),
            mean_funding_rate = mean(funds_raised_percent, na.rm = T),
            median_funding_rate = median(funds_raised_percent, na.rm = T),
            median_goal = median(goal_usd, na.rm = T),
            median_raised = median(pledged_usd, na.rm = T),
            count  = n()) %>% 
  mutate(platform = "Indiegogo")

cat_summary = union(ks_cat_summary %>% mutate(platform = "Kickstarter"),
                    ig_cat_summary %>% mutate(platform = "Indiegogo")) %>% 
  filter(!(category_broad %in% c("Kickstarter Only", "Indiegogo Only")))


ggplot(cat_summary, aes(x = category_broad)) +
  geom_col(aes(y = median_goal, color = platform), fill = NA, position = "dodge2") +
  geom_col(aes(y = median_funding_rate * median_goal, fill = platform), alpha = 0.5, position = "dodge2") +
  scale_fill_manual(values = platform_colors) + scale_color_manual(values = platform_colors) +
  theme_minimal() + theme(axis.text.x = element_text(angle = 90))


ggplot(cat_summary, aes(x = category_broad)) +
  geom_col(aes(y = median_goal, color = platform), fill = NA, position = "dodge2") +
  geom_col(aes(y = median_raised, fill = platform), alpha = 0.5, position = "dodge2") +
  scale_fill_manual(values = platform_colors) + scale_color_manual(values = platform_colors) +
  theme_minimal() + theme(axis.text.x = element_text(angle = 90))
```


```{r funding vs goal}
funding = bind_rows(
  ks_data %>% 
    select(raised_frac, goal_usd, pledged_usd) %>% 
    mutate(platform = "Kickstarter"),
  ig_data %>% 
    select(raised_frac, goal_usd, pledged_usd) %>% 
    mutate(platform = "Indiegogo")
) %>% 
  mutate(goal_bin = as_dollar_str(10^floor(log10(goal_usd))), 
         met_goal = as.integer(raised_frac >= 1),
         is_ks = as.integer(platform == "Kickstarter")) %>% 
  filter(goal_usd > 0,
         !is.infinite(goal_usd))



ggplot(funding %>% filter(raised_frac < 5, goal_usd >= 10, goal_usd < 10000000), 
       aes(x = goal_bin, y = raised_frac, fill = platform, color = platform)) +
  geom_violin(scale = "width", na.rm = TRUE, position = "dodge", bw = 0.05) +
  scale_color_manual(values = platform_colors) +
  scale_fill_manual(values = platform_colors)


ggplot(funding %>% filter(platform == "Kickstarter", raised_frac < 3), aes(x = raised_frac)) + 
  geom_histogram(binwidth = 0.05)
  

ggplot(funding %>% filter(platform == "Kickstarter") %>% slice_sample(n=1000), 
       aes(x = goal_usd, y = met_goal)) +
  geom_point(alpha = 0.2) +
  scale_x_log10()





```

```{r logistic regression}
logitmodel = glm(formula = met_goal ~ log10(goal_usd)*is_ks + log10(goal_usd) + is_ks, 
                  family = "binomial",
                  data = funding)

summary(logitmodel)

logitmodel$coefficients

p_met_coeffs_ig = logitmodel$coefficients[1:2]
p_met_coeffs_ks = p_met_coeffs_ig + logitmodel$coefficients[3:4]

```


```{r}
ggplot(data = funding %>% filter(platform == "Indiegogo", met_goal == 1, raised_frac < 5),
       aes(x = raised_frac)) +
  geom_histogram()

```

```{r}
logitmodel1 = glm(formula = met_goal ~ goal_usd*is_ks + goal_usd + is_ks, 
                  family = "binomial",
                  data = funding)

summary(logitmodel1)

logitmodel2 = glm(formula = met_goal ~ log10(goal_usd)*is_ks + log10(goal_usd) + is_ks, 
                  family = "binomial",
                  data = funding)

summary(logitmodel2)

funding_fit = funding %>% 
  mutate(p_goal_fitted_1 = fitted(logitmodel1),
         p_goal_fitted_2 = fitted(logitmodel2))

ggplot(funding_fit,
       aes(x = goal_usd, color = platform)) +
  geom_line(aes(y = p_goal_fitted_1), linetype = 1) +
  geom_line(aes(y = p_goal_fitted_2), linetype = 2) +
  scale_x_log10() +
  scale_color_manual(values = platform_colors)

funding_fit %>% 
  group_by(goal_bin, platform) %>% 
  summarize(success_rate = mean(met_goal),
            fitted_rate_1 = mean(p_goal_fitted_1),
            fitted_rate_2 = mean(p_goal_fitted_2),
            count = n(),
            .groups = "keep")
```




```{r JAGS eval=FALSE}


model_str = "model {
  for (i in 1:length(raised_frac)){
    raised_frac[i] ~ dgamma(alpha_frac, beta0 + beta1*goal[i])
  }
  alpha_frac ~ dgamma(2, 1)
  beta0 ~ dnorm(10, 10)
  beta1 ~ dnorm(0, 10)
}"

data_ig_under = funding %>% 
  filter(platform == "Indiegogo", raised_frac < 1, !is.na(goal_usd), !is.infinite(goal_usd))
data_jags = list(raised_frac = data_ig_under$raised_frac, goal = data_ig_under$goal_usd)
model = jags.model(textConnection(model_str), data = data_jags, n.chains = 3)
samples_ig_under = coda.samples(model = model, variable.names = c("alpha_frac", "beta0", "beta1"), n.iter = 2e3)

data_ig_met = funding %>% 
  filter(platform == "Indiegogo", raised_frac >= 1, !is.na(goal_usd), !is.infinite(goal_usd))
data_jags = list(raised_frac = data_ig_met$raised_frac-0.9999, goal = data_ig_met$goal_usd)
model = jags.model(textConnection(model_str), data = data_jags, n.chains = 3)
samples_ig_met = coda.samples(model = model, variable.names = c("alpha_frac", "beta0", "beta1"), n.iter = 2e3)

data_ks_met = funding %>% 
  filter(platform == "Kickstarter", raised_frac > 1, !is.na(goal_usd), !is.infinite(goal_usd)) %>% 
  slice_sample(n = 25000)
data_jags = list(raised_frac = data_ks_met$raised_frac-0.9999, goal = data_ks_met$goal_usd)
model = jags.model(textConnection(model_str), data = data_jags, n.chains = 3)
samples_ks_met = coda.samples(model = model, variable.names = c("alpha_frac", "beta0", "beta1"), n.iter = 2e3)


data_ks_under = funding %>% 
  filter(platform == "Kickstarter", raised_frac < 1, !is.na(goal_usd), !is.infinite(goal_usd)) %>% 
  slice_sample(n = 25000)
data_jags = list(raised_frac = data_ks_under$raised_frac+0.0001, goal = data_ks_met$goal_usd)
model = jags.model(textConnection(model_str), data = data_jags, n.chains = 3)
samples_ks_under = coda.samples(model = model, variable.names = c("alpha_frac", "beta0", "beta1"), n.iter = 2e3)
```

```{r compiling results}
compile_runs = function(samples){
  data = samples[[1]]
  for(i in 2:length(samples)){
    data = rbind(data, samples[[i]])
  }
  return(as.data.frame(apply(as.data.frame(data), 2, quantile, c(0.025, 0.5, 0.975))))
}

params_ig_under = compile_runs(samples_ig_under)
params_ig_met = compile_runs(samples_ig_met)
params_ks_under = compile_runs(samples_ks_under)
params_ks_met = compile_runs(samples_ks_met)

params_all = rbind(params_ig_under["50%",], params_ig_met["50%",], params_ks_under["50%",], params_ks_met["50%",])
row.names(params_all) = c("ig_under","ig_met","ks_under","ks_met")
params_all[c("ig_under","ks_under"),"alpha_frac"]

```


```{r summarize model}
full_logitmodel = rbind(p_met_coeffs_ks, p_met_coeffs_ig)
params_under = params_all[c("ks_under","ig_under"),]
params_met = params_all[c("ks_met","ig_met"),]
full_model = data.frame(row.names = c("Kickstarter", "Indiegogo"), 
                        c0 = full_logitmodel[,1], 
                        c1 = full_logitmodel[,2],
                        alpha_under = params_under[,"alpha_frac"],
                        alpha_met = params_met[,"alpha_frac"],
                        beta0_under = params_under[,"beta0"],
                        beta0_met = params_met[,"beta0"],
                        beta1_under = params_under[,"beta1"],
                        beta1_met = params_met[,"beta1"])

full_model

write_csv(full_model, "model_fit.csv")

```


```{r applying fit params}
pfrac = function(frac, goal, params){
  # Finds the probability of getting under a certain fraction of the funding goal
  mean_params = params["50%",]
  return(pgamma(frac, mean_params$alpha_frac, mean_params$beta0 + mean_params$beta1*goal))
}

qfrac = function(quantiles, goal, params){
  mean_params = params["50%",]
  return(qgamma(quantiles, mean_params$alpha_frac, mean_params$beta0 + mean_params$beta1*goal))
}

p_target = function(target, goal, model, platform){
  # Probability of raising at least a target number given a goal
  frac = target/goal
  params = model[platform,]
  p_met = 1/(1+exp(-params$c0-params$c1*log10(goal)))
  is_under = target < goal
  cdf_under = is_under*pgamma(frac, 
                              params$alpha_under, 
                              params$beta0_under+params$beta1_under*goal, 
                              lower.tail = FALSE)
  cdf_met = is_under + (1-is_under)*pgamma(frac-1, 
                                           params$alpha_met, 
                                           params$beta0_met+params$beta1_met*goal, 
                                           lower.tail = FALSE)

  #print(c(p_met, cdf_under, cdf_met))
  if(platform == "Kickstarter"){
    return(p_met*cdf_met)
  }else(
    return(p_met*cdf_met + (1-p_met)*cdf_under)
  )
}

```

```{r}
goal = 100000
goal * qfrac(c(0.25,0.75), goal, params_ks_met)

p_target(500, 781, full_model, "Kickstarter")

optimal_goal(500, full_model, "Kickstarter")

goal = (0:100)*100
y = p_target(8000, x, full_model, "Kickstarter")
plot(x,y)


data = data.frame()
for(i in 2:7){
  goal = 10^i
  target = goal*(0:300)/100
  p = p_target(target, goal, full_model, "Indiegogo")
  data = rbind(data,
               data.frame(p = p_target(target, goal, full_model, "Indiegogo"), 
                          frac = target/goal, platform = "Indiegogo", goal = factor(as_dollar_str(goal))),
               data.frame(p = p_target(target, goal, full_model, "Kickstarter"), 
                          frac = target/goal, platform = "Kickstarter", goal = factor(as_dollar_str(goal))))
}


ggplot(data, aes(x = frac, y = p, color = platform)) +
  geom_line() +
  scale_color_manual(values = platform_colors) +
  facet_wrap(vars(goal))
```

```{r bayesian analytical}
alpha_jags = 5.300e-01

n = nrow(data_ig_under)

alpha0 = n*alpha_jags + 1
beta0 = 1 + (sum(data_ig_under$raised_frac))

beta_expected = alpha0/beta0 

ggplot() +
  geom_histogram(aes(x = rgamma(n, 2, beta_expected)))

ggplot() +
  geom_histogram(aes(x = rgamma(n, 0.53, 2.847)))

ggplot(data_ig_under, aes(x = raised_frac)) +
  geom_histogram()

```